feat: Attempt to use EthJs libraries as alternative since `unlockAccount` in Web3.js Beta not ready
Error: [ethjs-account] invalid address value "0x677a0038a9eb2cf32d9f6bcc6ce74070692a8ca4c8c6344cf3da0013177183a2" not a valid hex string